[theme]
primaryColor = "#0e4c92"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#e0e8f0"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
